Adds an article about XSS attacks and its prevention.
guardrailsio/awesome-java-security pull request #3
Opened 2019-01-23 18:35 UTC by ilhan-mstf

2019-01-23 23:11 UTC, streichsbaer requested changes
Thanks for the contribution, @ilhan-mstf 

Please fix the typo, then it’s good to be merged!

2019-01-23 23:11 UTC, streichsbaer commented on README.md
> +- [Prevent cross-site scripting (XSS) attacks](https://www.ibm.com/developerworks/library/se-prevent-cross-site-scripting-attacks/index.html) - This article explains how XSS attacks work and suggests
There’s a typo in methodology.

2019-01-24 06:24 UTC, ilhan-mstf commented on README.md
> +- [Prevent cross-site scripting (XSS) attacks](https://www.ibm.com/developerworks/library/se-prevent-cross-site-scripting-attacks/index.html) - This article explains how XSS attacks work and suggests
Thanks for the feedback, I've just fixed the typo.

2019-01-24 08:40 UTC, ghost approved these changes
LGTM :shipit: Thanks for your contribution!

2019-01-24 09:15 UTC, r0flc0pt4 approved these changes
LGTM!

2019-01-24 09:17 UTC, streichsbaer approved these changes

2019-01-24 09:17 UTC, merged